name: Build & Publish ClickOnce Release

on:
  push:
    tags:
      - 'v*.*.*'   # Triggers only when you push a version tag like v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Restore packages
      run: dotnet restore

    - name: Publish ClickOnce
      run: dotnet publish ./CalculatorWPF.csproj -c Release -o ./publish /p:PublishSingleFile=false

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: publish/**/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
